### ISSUE TITLE
Take a look at `fades`

### ISSUE THREAD

**Issue by facundobatista** [ironfroggy/feet#13]
Hello!

I'm very excited to learn about `feet`, I think it would be a good benefit to the Python ecosystem to have a way to distribute executables like this.

More, I'm sure about it. I even had this in mind (but no clue how to attack the problem) because it would be an ideal complement to [fades](https://github.com/PyAr/fades/). 

`fades` is a system that automatically handles the virtualenvs in the cases normally found when writing scripts and simple programs, and even helps to administer big projects.

I see that you handle already some package installing, but you may want to take a look to `fades` as it provides a lot of options and automatic stuff already, and several ways to describe that needed packages, and even handle automatic upgrades, and several options else.

`fades` is a pure Python project, so you may just integrate it directly in `feet`, and just call it and let it do all the work.

Please, let me know what you think about this, if it fits or why not, if you have better ideas around this, we can always add to `fades` some missing piece for everything work together. 

Thanks!

**Comment by ironfroggy** [comment]
Feet is itself a sort of virtualenv, so anything managing them is a bit redundant. Fades does look like an interesting tool, and I'll probably dig into it to learn more for other uses. Thanks for the suggestion and for checking out Feet.
